project:
  type: website
  output-dir: .

website:
  title: "Mads Nørgaard"  
  search: false
  navbar:
    right: 
      - text: "research"
        href: research.qmd
      - text: "teaching" 
        href: "teaching.qmd" 
      - text: "cv"
        href: cv.qmd
      - icon: envelope
        href: "mailto:mnr@ps.au.dk"
        aria-label: "Email"

  page-footer:
    left:
      - text: "email &nbsp;"
        href: "mailto:mnr@ps.au.dk"
      - text: "university website"
        href: "https://www.au.dk/mnr@ps.au.dk"

format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: false
    link-external-newwindow: true
    include-after-body: carousel.html



 
